mrigaankzoro/Hacktoberfest24

contributor.md

i have styled styled the contri.md nicely

styled the contributor.md 

---

GenerateRandomString.cpp

Add Random String Generater using  cpp.

Create Generate Random String in c++

---

CheckPrime.cpp

Added program to check if a number is Prime or not in C++ using a very efficient approach.

Check Prime in C++

---

algo_find_largest_num.cpp

Algorithm to find Largest Number.

fix-issue-18

---

Morris_Traversal_Preorder.cpp
Reverse_Single_LinkedList.cpp

Easily reverse a singly linked list in C++

Reverse_Single_LinkedList and Preorder Morris Traversal | Issue #25 & #26

---

Kadane's_Algorithm

Kindly review my code for the Kadane's Algorithm. It is the most efficient approach for finding maximum sum subarray from array with positive and negative integers.

 Kadane's_Algorithm

---

Longes_substring_without_repeating_characters.cpp

Longest substring without repeating characters using Sliding Window approach
We use two pointers (left and right) to represent a sliding window. The window contains the substring we are currently examining for unique characters.
We move the right pointer over the string, and if a repeated character is found (i.e., the character already exists in the current window), we move the left pointer to just after the previous occurrence of the repeated character to start a new substring.
Hash Map (unordered_map):
The hash map keeps track of the last index where each character appeared. This helps us quickly find if a character repeats within the current window.
Time Complexity:
O(n), where n is the length of the string. Each character is processed at most twice (once by the right pointer and once …

Hi @mrigaankzoro , i have added the solution to #23 , Kindly check the solution and merge my PR

---

snake_game.cpp

Snake Game in cpp

---

Largest_number.cpp
calculator GUI prog/improved_cALC.py

Made a Good and Modern GUI calculator using Python Tkinter.

Calculator

---

.vscode/c_cpp_properties.json
Container with Most Water/solution.py

issue no:
#30 
hello @mrigaankzoro thank you for assigning it to me along with label.

container with most water with solution

---

karatsuba_algorithm.cpp

This is the implementation of the algorithm mentioned in issue #33.

feat: karatsuba's algorithm (aliqyan-21)

---

HeyBro.java

just added a file

---

tribonacci_using_DP.cpp

Adding a program for Nth Tribonacci Number which can be solved using Dynamic Programming (Memoization), and serves as a natural extension of the fibonacci using DP Problem

Created tribonacci_using_DP.cpp

---

Fractional Knapsack Problem/README.md
Fractional Knapsack Problem/fractional_knapsack.py

I have implemented the fractional knapsack problem as mentioned in the issue i had raised.
The approach is selecting fractional parts of items to maximize total value, using a greedy algorithm to prioritize items with the highest value-to-weight ratio.
I have also added a readme file explaining the algorithm and code and given example testcase as well.
Please have a look and merge this pull request under Hacktoberfest 2024
Thank you

To add algorithm for fractional knapsack problem #41

---

Bubble Sort.cpp

I have added code for Bubble Sort in C++. Please merge my code.

Bubble Sort.cpp

---

buy_and_sell_stock.java

Java code to find the  Best Time to Buy and Sell Stock.

program to find  Best Time to Buy and Sell Stock

---

largest.cpp

A C++ program to find the largest number

added a c++ program

---

reverse_k_sizedGrpsInLL.cpp

This is a c++ program reversing nodes in k-sized groups in a linked list, along with helper functions to create and print the list.
Also, please add the needed tags.
Thank you :-)

Reverse K-sized linked list

---

Matrix multiplication.cpp

added matrix multiplication in c++
solved issue #61

Create Matrix multiplication.cpp

---

Moore's Voting Algorithm/MooresVotingAlgorithm.cpp

Moore's Voting Algorithm added  . Please accept the PR

Moore's Voting Algorithm added

---

VerticalOrderTraversal_binarytree.cpp

Hey @mrigaankzoro I have added the code for Vertical Order Traversal in Binary Search Tree using C++. The implementation includes a detailed explanation of the concept behind vertical order traversal and also handles the edge cases.
I kindly request that you merge this PR as part of Hacktoberfest 2024. Looking forward to your feedback and contributing further!

Added Vertical Order Traversal for Binary Tree in cpp

---

PaintersPartition.cpp

Implement solution for Painter's Partition Problem. Added user input for board lengths and number of painters. Includes binary search optimization to minimize painting time.

 Added Painter's Partition Problem Solution in C++ language.

---

calculator_using_switchcase.cpp

calculator_using_switchcase.cpp

---

Graph/vertical_traversal.cpp

Hello @mrigaankzoro 
I have added the code of  "vertical traversal of the binary tree"  and also written the concept involved  and obervation related to it.  I have described work the given function formed under this program.
kindly , merge this PR under the hacktoberfest 2024.

Vertical traversal of binary tree #58

---

quick_sort.py

Adding Quick Sort code in Python.

Quick sort python

---

AllSortingAlgo/bucket_sort.java

Created bucket_sort.java

---

PrimesInGivenRange.cpp

Made a short program to output all of the prime numbers in a given range (inclusive)

Created PrimesInGivenRange.cpp

---

algo_find_largest_num.cpp

This version makes the code more modular by using a function to find the largest element and ensures that the number of elements is positive before proceeding.
please assign

function to find the largest element

---

LongestSubsetWithZeroSum.cpp

This PR introduces a function LongestSubsetWithZeroSum that calculates the length of the longest subarray with a sum of zero in an input vector. The algorithm uses a hash map to optimize the time complexity, improving it from a brute-force solution to a more efficient O(n) approach.
Key Changes:
Implemented the LongestSubsetWithZeroSum function.
Optimized the subarray search using a prefix sum and hash map to track cumulative sums.
Added test cases in the main function to validate the logic with an example array.
Performance:
Time Complexity: O(n), where n is the size of the input array.
Space Complexity : O(n) due to the use of an unordered map for storing cumulative sums.
Testing:
Tested with example array: {6, 1, -1, 2, -1, 4, -5, -5}.
Verified that the output is correct, returning the …

Add function to find the longest subarray with zero sum

---

CPU scheduling algorithms/Non-Preemptive algos/fcfs.cpp
CPU scheduling algorithms/Non-Preemptive algos/non-preemptive_priority.cpp
CPU scheduling algorithms/Non-Preemptive algos/sjf.cpp
CPU scheduling algorithms/Preemptive algos/round_robin.cpp
CPU scheduling algorithms/Preemptive algos/srtf.cpp
CPU scheduling algorithms/explanation.md

algos:
non-preemptive:
- first come first serve
- shortest job first
- priority
preemptive:
- round robin
- shortest remaining time first

feat: added scheduling algos with explanation.md

---

Finance Manager/index.html
Finance Manager/script.js
Finance Manager/styles.css

Finance Manager

---

count-primes.py

[204. Count Primes](https://leetcode.com/problems/count-primes/)
Medium
Given an integer n, return the number of prime numbers that are strictly less than n.
Input: n = 10
Output: 4
Explanation: There are 4 prime numbers less than 10, they are 2, 3, 5, 7.
Example 2:
Input: n = 0
Output: 0
Example 3:
Input: n = 1
Output: 0
Constraints:
0 <= n <= 5 * 106
I have used Sieve of Eratosthenes to solve this problem, it achieves

Added Leetcode 204 Count Primes

---

Validate Binary Search Tree

This contribution adds a C++ implementation for validating whether a binary tree is a valid Binary Search Tree (BST). The algorithm leverages recursion to traverse the tree and checks if every node adheres to the properties of a BST, where for each node, the left subtree contains only values less than the node, and the right subtree contains only values greater.

 Validate Binary Search Tree Code

---

Network_delay_time.cpp

added solution for problem titled network delay time in leetcode

Network_delay_time.cpp

---

count no of subarrays

Create count no of subarrays

---

Matrix multiplication

The program reads dimensions and values for two matrices.
It checks if matrix multiplication is possible by comparing dimensions.
If compatible, it multiplies the matrices and stores the result.
Finally, it outputs the resulting matrix.
#61

Create Matrix multiplication
